SUBJECTS = ['AAS', 'AAU', 'ACC', 'ACH', 'ADV', 'AFH', 'AFL', 'AFS', 'AIM', 'AMR', 'AMS', 'ANP', 'ANS', 'ANT', 'APC',
            'ARB', 'ARH', 'ARN', 'ARS', 'ART', 'AST', 'ATM', 'ATS', 'BCB', 'BCD', 'BCP', 'BEE', 'BGE', 'BHO', 'BHT',
            'BIO', 'BLS', 'BMB', 'BME', 'BMO', 'BNB', 'BNG', 'BPB', 'BSB', 'BSE', 'BUS', 'CAR', 'CBN', 'CCS', 'CDT',
            'CEA', 'CEB', 'CEC', 'CED', 'CEE', 'CEF', 'CEG', 'CEH', 'CEI', 'CEJ', 'CEK', 'CEL', 'CEM', 'CEN', 'CEP',
            'CEQ', 'CER', 'CES', 'CET', 'CEV', 'CEX', 'CEY', 'CEZ', 'CFS', 'CHE', 'CHI', 'CIV', 'CLG', 'CLL', 'CLP',
            'CLS', 'CLT', 'CME', 'CNH', 'CNS', 'COR', 'CPE', 'CSE', 'CSK', 'CSL', 'CSM', 'CST', 'CUE', 'CWL', 'DAN',
            'DEC', 'DIA', 'DLF', 'DLG', 'DLI', 'DLL', 'DLM', 'DLR', 'DLS', 'DLT', 'DPA', 'EAS', 'EBH', 'ECO', 'EDP',
            'EDU', 'EEL', 'EEO', 'EFL', 'EGC', 'EGL', 'EHI', 'EHM', 'EMP', 'ENP', 'ENS', 'ENV', 'EPP', 'EPS', 'ESA',
            'ESC', 'ESE', 'ESG', 'ESI', 'ESL', 'ESM', 'ESS', 'EST', 'ESU', 'EUR', 'EXT', 'FAA', 'FIN', 'FLA', 'FLC',
            'FLG', 'FLI', 'FLR', 'FRN', 'FSC', 'FSD', 'FSI', 'FSY', 'FTH', 'GEO', 'GER', 'GIS', 'GLS', 'GRD', 'GRK',
            'GSS', 'HAA', 'HAC', 'HAD', 'HAH', 'HAL', 'HAN', 'HAO', 'HAP', 'HAS', 'HAT', 'HAX', 'HAY', 'HBA', 'HBB',
            'HBC', 'HBH', 'HBI', 'HBM', 'HBN', 'HBO', 'HBP', 'HBW', 'HBY', 'HCB', 'HDB', 'HDC', 'HDE', 'HDG', 'HDH',
            'HDI', 'HDM', 'HDO', 'HDP', 'HDR', 'HDS', 'HDV', 'HFA', 'HFN', 'HHP', 'HIN', 'HIS', 'HMC', 'HMF', 'HMH',
            'HMI', 'HMK', 'HMM', 'HMO', 'HMP', 'HMR', 'HNC', 'HND', 'HNE', 'HNG', 'HNH', 'HNI', 'HNP', 'HON', 'HPD',
            'HPH', 'HSC', 'HSH', 'HSQ', 'HTM', 'HTO', 'HUE', 'HUF', 'HUG', 'HUI', 'HUL', 'HUM', 'HUR', 'HUS', 'HWC',
            'HWD', 'HWE', 'HWF', 'HWG', 'HWI', 'HWL', 'HWP', 'HWS', 'HWT', 'HWX', 'IAP', 'IAS', 'ICP', 'IDA', 'IDC',
            'IEC', 'IEP', 'IIU', 'IMB', 'IMS', 'INS', 'INT', 'IRH', 'ISE', 'ISH', 'ISN', 'ISP', 'ISS', 'ITL', 'ITS',
            'JDH', 'JDS', 'JNH', 'JNS', 'JPN', 'JRN', 'KIS', 'KOR', 'KRH', 'KRS', 'LAC', 'LAN', 'LAT', 'LBR', 'LCR',
            'LDR', 'LDS', 'LES', 'LHD', 'LHW', 'LIA', 'LIB', 'LIN', 'LIS', 'LRN', 'LSE', 'MAE', 'MAP', 'MAR', 'MAT',
            'MBA', 'MCB', 'MCR', 'MEC', 'MGT', 'MKT', 'MSA', 'MSC', 'MSE', 'MSI', 'MSM', 'MSP', 'MST', 'MUS', 'MVL',
            'NET', 'NEU', 'NLN', 'NSE', 'NSM', 'NTR', 'OCN', 'OCR', 'P71', 'PAM', 'PDR', 'PEC', 'PEM', 'PER', 'PEW',
            'PHI', 'PHY', 'POL', 'POR', 'PRS', 'PSH', 'PSY', 'QRS', 'RLS', 'RSP', 'RUS', 'SAN', 'SAS', 'SBC', 'SBS',
            'SBU', 'SCH', 'SCI', 'SCN', 'SEI', 'SGE', 'SGL', 'SKL', 'SKT', 'SLN', 'SLS', 'SLV', 'SOC', 'SPD', 'SPN',
            'SPU', 'SSC', 'SSE', 'SSI', 'SSO', 'SUS', 'SWA', 'SWE', 'TAF', 'TCE', 'THR', 'TMP', 'TNT', 'TRC', 'TRH',
            'TRK', 'TVS', 'UDV', 'UPS', 'URE', 'USB', 'USP', 'WHU', 'WNH', 'WNS', 'WPT', 'WRT', 'WSE', 'WST', 'WVR',
            'YCS', 'YDH', 'ZZZ', 'WVR']
